export const authorityMapping: Record<string, string> = {
  L01X: "Köln",
  L07W: "Schwerte",
  L0FK: "Bergen auf Rügen",
  L0HM: "Schwerin",
  L0HY: "Stralsund",
  L0JC: "Duisburg",
  L0KS: "Mössingen",
  L0MF: "Neubrandenburg",
  L0WT: "Stuttgart",
  L1HY: "Oldenburg",
  L1LT: "Südangeln",
  L1M1: "Schwesing",
  L1NL: "Itzehoe",
  L1NT: "Schenefeld",
  L1NX: "Ahrensburg",
  L1PP: "Ellerau",
  L1PW: "Lübeck",
  L1PX: "Lübeck",
  L1T5: "Hamburg - Nord",
  L1TC: "Hamburg - Altona",
  L1TL: "Hamburg - Barmbek",
  L1TP: "Bergedorf",
  L1TV: "Hamburg - Billstedt",
  L1V5: "Hamburg - Eimsbüttel",
  L1VN: "Hamburg - Lokstedt",
  L1VY: "Hamburg - St. Pauli",
  L1W8: "Hamburg - Wandsbek",
  L1Y1: "Dransfeld",
  L1Y2: "Duderstadt",
  L1YC: "Göttingen",
  L1ZG: "Hardegsen",
  L2CF: "Delmenhorst",
  L2CJ: "Emden",
  L353: "Sulzbach/Saar",
  L6Z8: "Oberhausen",
  L72G: "Schwalmtal",
  L73Y: "Bonn",
  L79V: "Sankt Augustin",
  L7TH: "Iserlohn",
  L88N: "Heidenheim",
  L933: "Freiburg im Breisgau",
}
