export const authorityMapping: Record<string, string> = {
  L01X: "Köln",
  L07W: "Schwerte",
  L0FK: "Bergen auf Rügen",
  L0FT: "Greifswald",
  L0HM: "Schwerin",
  L0HY: "Stralsund",
  L0JC: "Duisburg",
  L0KS: "Mössingen",
  L0MF: "Neubrandenburg",
  L0WT: "Stuttgart",
  L1HY: "Oldenburg",
  L1LT: "Südangeln",
  L1M1: "Schwesing",
  L1NL: "Itzehoe",
  L1NT: "Schenefeld",
  L1NX: "Ahrensburg",
  L1PP: "Ellerau",
  L1PW: "Lübeck",
  L1PX: "Lübeck",
  L1T5: "Hamburg - Nord",
  L1TC: "Hamburg - Altona",
  L1TL: "Hamburg - Barmbek",
  L1TP: "Bergedorf",
  L1TV: "Hamburg - Billstedt",
  L1V5: "Hamburg - Eimsbüttel",
  L1VN: "Hamburg - Lokstedt",
  L1VV: "Hamburg",
  L1VY: "Hamburg - St. Pauli",
  L1W8: "Hamburg - Wandsbek",
  L1Y1: "Dransfeld",
  L1Y2: "Duderstadt",
  L1YC: "Göttingen",
  L1ZG: "Hardegsen",
  L1ZN: "Northeim",
  L2CF: "Delmenhorst",
  L2CH: "Emden",
  L2CJ: "Emden",
  L2HY: "Leer",
  L2ZJ: "Mainz",
  L353: "Sulzbach/Saar",
  L3HV: "Berlin",
  L3R3: "Fürstenberg/Havel",
  L4FC: "Deutsches Generalkonsulat Toronto, CA",
  L4K0: "Deutsche Botschaft, QA, Doha",
  L4KL: "Deutsche Botschaft TH, Bangkok",
  L4TN: "Deutsche Botschaft BE, Brüssel",
  L4VM: "Deutsche Botschaft LU, Luxemburg",
  L4VW: "Deutsche Botschaft AT, Wien",
  L5H6: "Darmstadt",
  L5JH: "Birkenau",
  L644: "Witzenhausen",
  L6Z8: "Oberhausen",
  L726: "Schwalmtal",
  L72G: "Schwalmtal",
  L73R: "Bonn",
  L73T: "Bonn",
  L73Y: "Bonn",
  L73Z: "Bonn",
  L79V: "Sankt Augustin",
  L7T2: "Meschede",
  L7TH: "Iserlohn",
  L84T: "Leipzig",
  L88N: "Heidenheim",
  L8PP: "Leinzell",
  L8WN: "Mannheim",
  L933: "Freiburg im Breisgau",
  L97C: "Sasbach",
  L9R4: "Maselheim",
  L9X9: "Plettenberg",
  LF56: "Schrobenhausen",
  LG10: "Oberhaid",
  LGG1: "Haibach",
  LGNC: "Kempten (Allgäu)",
  LH1H: "München",
}
